server:
  port: 9090
spring:
  application:
    name: Doctor_Patient_Management
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 10
    password: bagavai
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: oracle11am
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
